version: '3.7'
services:
  werewolf-node-docker:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # target: base
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: werewolf-node-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: yarn start
  werewolf-react-docker:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes: 
      - ./frontend:/usr/src/app/
      - /usr/src/app/node_modules
    container_name: werewolf-react-docker
    expose: 
      - '9000'
    ports: 
      - '9000:9000'
    command: yarn start